services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: climate-api
    volumes:
      - ../external_data/era5_temperature_1940_2024.zarr:/app/external_data/era5_temperature_1940_2024.zarr:ro

